name = "JLSponge"
uuid = "2565b3f7-f603-4bd1-a364-d6b055d0cbec"
authors = ["suyaoIndigo <j.c.f.gauss@sjtu.edu.cn> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
